#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_back_acceuil:
    path: /back/acceuil
    controller: App\Controller\BackAcceuilController::index
    methods: ['GET']